### ISSUE TITLE
Low fidelity

### ISSUE THREAD

**Issue by JosephGros** [chas-academy/u02-redesign-grupp-33#58]

**Comment by JosephGros** [comment]
Vi har tillsammans gjort low fidelity för både Desktop och Mobil.

![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/5c0e617f-fea0-4b24-9a49-cb9207e5dd16)


![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/8867a882-0f6e-4879-830d-57380347887a)

**Comment by Superfelicia** [comment]
[Designdokumentation.pdf](https://github.com/chas-academy/u02-redesign-grupp-33/files/13403673/Designdokumentation.pdf)
