### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by JosephGros** [chas-academy/u02-redesign-grupp-33#60]

**Comment by emilia-harden** [comment]
![Image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/133894577/841d5292-f490-4ca9-b18c-1be59dd6eaf4)



![Image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/133894577/2d528928-42c7-4026-8012-e2891934ea5d)




![Image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/133894577/0a4f2303-0992-4e76-8de8-2b36e95c3935)



![Image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/133894577/989a9f1b-4a9f-45e3-8cb3-65091df2c5eb)
