### ISSUE TITLE
Bakgrundsbilder

### ISSUE THREAD

**Issue by DenjinM** [chas-academy/u02-redesign-grupp-33#72]

**Comment by DenjinM** [comment]
Stina och Simon ville båda att varje bild ska passa varje sida man är inne på, för att få en ännu bättre överblick, och känslan av vad för typ för hemsida de är inne på

**Comment by JosephGros** [comment]
Jag har framtagit ex antal bilder med hjälp av AI. Både för hero bilder men också logga för medlemmar och restos nya logga. 


![food festival 1](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/bca40a16-fbf2-4ddd-a686-dc1221aa3aa0)


![netherlands 3](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/1d256021-4108-4f6f-a0e8-90baf4703873)


![food 8](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/64eb48f0-9666-4992-b4a5-4aab8021baa4)


![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/e4e90350-89db-46e1-b954-
5fa9152daa4d)


![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/1e680f50-d4cb-41d7-8dca-
e0c061ec705b)


![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/514bfc51-a5f6-445f-8a94-b48449b538a1)


![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/6c09282a-9578-41eb-b335-5ac204316df1)


![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/a5c71b7e-bc09-4a60-aa8e-f67cb48fd0a4)

**Comment by JosephGros** [comment]
![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/e4e90350-89db-46e1-b954-e0c061ec705b)


![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/1e680f50-d4cb-41d7-8dca-5fa9152daa4d)

**Comment by JosephGros** [comment]
![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/45e5739b-1aba-43da-b9b3-7dfd4d9d5e51)

![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/22944a3a-88c1-4d6b-84cf-4d27dcf5b884)

![image](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/2150dda4-f6ba-471b-99e1-c5fdf9e45bfd)
