### ISSUE TITLE
Logo-bilder

### ISSUE THREAD

**Issue by DenjinM** [chas-academy/u02-redesign-grupp-33#73]

**Comment by DenjinM** [comment]
Stina tyckte det var tråkigt och var inte nöjd med hur medlemmarna presenterades, där det var ganska tomt med bilder som beskrev eller gav känslan av vad för cateringföretag det är. Hon ville det skulle framhävas tydligare.

**Comment by JosephGros** [comment]
Jag har framtagit ex antal bilder med hjälp av AI. Både för hero bilder men också logga för medlemmar och restos nya logga.

![Joes louisiana kitchen](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/6c389eef-a4fd-4f95-a5ba-2479e1a36d23)
![medlem 13](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/69ec678d-b2e1-47e8-a0f5-f21e1da80a09)
![medlem 14](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/f7b0930d-61b6-4509-8f71-593e92f46d5f)
![Charcutcut](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/71e1be5a-e760-4f5e-b148-35398c2e3155)
![medlem 16](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/e7693263-8f84-46bf-9ff4-2da5ab9446df)
![mean burgers](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/09f1e274-acb5-4f79-a412-d88b76b28d0f)
![Gyro truck](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/fa7fc592-cb16-44ae-bdcf-cbd94ffffc93)
![veg logo](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/e489cd33-6e13-4bcb-bfe5-8c8c0ab4e528)
![Nacho mania](https://github.com/chas-academy/u02-redesign-grupp-33/assets/144314897/19aa54ba-824b-4048-bf59-591b80a0f56f)
